### ISSUE TITLE
Question: TaskFailed: error: serial group task Signaling was canceled due to subtask Signaling/Timeout15000ms (once) error: WebSocket connection failed

### ISSUE THREAD

**Issue by shriyajuneja** [aws/amazon-chime-sdk-js#2351]
### What happened and what did you expect to happen?

 Amazon Chime SDK for Javascript is unable to establish web socket connection while trying to start meeting. What could be the reason for web socket failure ?

```
will retry due to status code TaskFailed and error: serial group task AudioVideoStart/27fc8326-977d-48a3-b38d-1b43b84b0706/0c892206-723c-d3be-d520-b56a469640a6 was canceled due to subtask AudioVideoStart/27fc8326-977d-48a3-b38d-1b43b84b0706/0c892206-723c-d3be-d520-b56a469640a6/Timeout15000ms error: serial group task AudioVideoStart/27fc8326-977d-48a3-b38d-1b43b84b0706/0c892206-723c-d3be-d520-b56a469640a6/Timeout15000ms/Peer was canceled due to subtask AudioVideoStart/27fc8326-977d-48a3-b38d-1b43b84b0706/0c892206-723c-d3be-d520-b56a469640a6/Timeout15000ms/Peer/SubscribeAndReceiveSubscribeAckTask (once) error: serial group task Signaling was canceled due to subtask Signaling/Timeout15000ms (once) error: WebSocket connection failed
```
```
Start failed: The connection failed. See the error message for more details. due to error Error: serial group task AudioVideoStart/27fc8326-977d-48a3-b38d-1b43b84b0706/0c892206-723c-d3be-d520-b56a469640a6 was canceled due to subtask AudioVideoStart/27fc8326-977d-48a3-b38d-1b43b84b0706/0c892206-723c-d3be-d520-b56a469640a6/Timeout15000ms error: serial group task AudioVideoStart/27fc8326-977d-48a3-b38d-1b43b84b0706/0c892206-723c-d3be-d520-b56a469640a6/Timeout15000ms/Peer was canceled due to subtask AudioVideoStart/27fc8326-977d-48a3-b38d-1b43b84b0706/0c892206-723c-d3be-d520-b56a469640a6/Timeout15000ms/Peer/SubscribeAndReceiveSubscribeAckTask (once) error: serial group task Signaling was canceled due to subtask Signaling/Timeout15000ms (once) error: WebSocket connection failed.
```
```notifying event: WebSocketClosed
no connection requests to service
event: signalingDropped
notifying event: WebSocketFailed
stopped pinging (WebSocketFailed)
Opening signaling connection took 23 ms
```

The above issue was reproducible on 5/10 calls.

### Have you reviewed our existing documentation?

- [X] GitHub [issues](https://github.com/aws/amazon-chime-sdk-js/issues)
- [X] FAQs [page](https://aws.github.io/amazon-chime-sdk-js/modules/faqs.html)
- [X] README [page](https://github.com/aws/amazon-chime-sdk-js#amazon-chime-sdk-for-javascript)
- [X] Feature-specific [guides](https://github.com/aws/amazon-chime-sdk-js#guides)

### Reproduction steps

NA

### Amazon Chime SDK for JavaScript version

2.25.0

### What browsers are you seeing the problem on?

Chrome

### Browser version

103.0.0.0

### Meeting and Attendee ID Information.

Problematic attendeeId : 0c892206-723c-d3be-d520-b56a469640a6
Meeting Id: 27fc8326-977d-48a3-b38d-1b43b84b0706

### Browser console logs

[logs.txt](https://github.com/aws/amazon-chime-sdk-js/files/9047734/logs.txt)

**Comment by tenge-amzn** [comment]
Does this happen all the time or randomly?
You can do a quick check from end-user's network to see if the domain/port is blocked.

```
curl https://check.z1.ue1.m.chime.aws
Hello%
```

**Comment by xuesichao** [comment]
Close the issue due to inactivity. Feel free to reopen it.
